var CANVAS_WIDTH = 1024;
var CANVAS_HEIGHT = 768;

var FPS_TIME      = 1000/24;
var DISABLE_SOUND_MOBILE = true;

var STATE_LOADING = 0;
var STATE_MENU    = 1;
var STATE_HELP    = 1;
var STATE_GAME    = 3;

var ON_MOUSE_DOWN = 0;
var ON_MOUSE_UP   = 1;
var ON_MOUSE_OVER = 2;
var ON_MOUSE_OUT  = 3;
var ON_DRAG_START = 4;
var ON_DRAG_END   = 5;

var STATE_GAME_ROLL_IN       = 0;
var STATE_GAME_BALL_MOVE     = 1;
var STATE_GAME_ROLL_OUT      = 2;
var STATE_GAME_SHOOTING      = 3;
var STATE_GAME_ATTRACT_BALLS = 4;

var STEP_LENGTH = 2;
var BALL_COLORS = 5;
var BALL_ROLLING_IN;
var BALL_SHOOTED_SPEED = 36;
var COMBO_VALUE ;
var EXTRA_SCORE;
var BALL_DIAMETER;
var BALL_RADIUS;
var BALL_DIAMETER_SQUARE;